<template>
    <div class="info-section track-in">
        <h1 class="sm:text-8xl text-6xl tron-text-blue mb-3">William Keirn</h1>
        <ScrollMenu @scroll-clicked="emitScroll" />
    </div>
</template>

<script setup lang="ts">
const { observedElement, elementClass, interOptions, interCallback, observer } = useIntersect();
onMounted(() => {
    observedElement.value = document.querySelector(".track-in");
    elementClass.value = "track-in-contract";
    interOptions(null, 0);
    interCallback();
    observer.observe(observedElement.value as Element);
});

const emit = defineEmits<{
    (e: 'scrollClick', id: string): void,
}>();

function emitScroll(id: string): void{
    emit('scrollClick', id);
}
</script>

<style>
    .info-section {
        margin: 0;
        margin-left: 8rem;
        margin-bottom: 50%;
        text-align: left;
        position: absolute;
        top: 50%;
        -ms-transform: translateY(-50%);
        transform: translateY(-50%);
    }

    .track-in-contract {
        -webkit-animation: tracking-in-contract 0.8s cubic-bezier(0.215, 0.610, 0.355, 1.000) both;
        animation: tracking-in-contract 0.8s cubic-bezier(0.215, 0.610, 0.355, 1.000) both;
    }

    /* ----------------------------------------------
    * Generated by Animista on 2023-3-12 13:0:21
    * Licensed under FreeBSD License.
    * See http://animista.net/license for more info. 
    * w: http://animista.net, t: @cssanimista
    * ---------------------------------------------- */

    /**
    * ----------------------------------------
    * animation tracking-in-contract
    * ----------------------------------------
    */
    @-webkit-keyframes tracking-in-contract {
    0% {
        letter-spacing: 0.5em;
        opacity: 0;
    }
    40% {
        opacity: 0.6;
    }
    100% {
        letter-spacing: 0.1em;
        opacity: 1;
    }
    }
    @keyframes tracking-in-contract {
    0% {
        letter-spacing: 0.5em;
        opacity: 0;
    }
    40% {
        opacity: 0.6;
    }
    100% {
        letter-spacing: 0.1em;
        opacity: 1;
    }
    }
</style>